Training...
Epoch 0
Training Iterations:   0%|                                                                                                                                                                                                                                                                | 0/8 [00:12<?, ?it/s]
Traceback (most recent call last):
  File "/user/as6154/dissert/gpt2.py", line 173, in <module>
    output = model(input_seq)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/dissert/gpt2.py", line 89, in forward
    output = self._backbone(inputs_embeds=embeds).last_hidden_state
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1235, in forward
    outputs = block(
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 757, in forward
    feed_forward_hidden_states = self.mlp(hidden_states)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 681, in forward
    hidden_states = self.act(hidden_states)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/transformers/activations.py", line 56, in forward
    return 0.5 * input * (1.0 + torch.tanh(math.sqrt(2.0 / math.pi) * (input + 0.044715 * torch.pow(input, 3.0))))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 938.00 MiB. GPU  has a total capacity of 79.14 GiB of which 798.75 MiB is free. Including non-PyTorch memory, this process has 78.35 GiB memory in use. Of the allocated memory 77.76 GiB is allocated by PyTorch, and 101.37 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)